// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJV7ePDR14V2Jg5iDgO879K10y9-UV8BM',
    appId: '1:969769036024:web:9fd8d5f5fec67f27f0730d',
    messagingSenderId: '969769036024',
    projectId: 'fitmetricsusers',
    authDomain: 'fitmetricsusers.firebaseapp.com',
    storageBucket: 'fitmetricsusers.firebasestorage.app',
    measurementId: 'G-MHV74EE5BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6LlzGIdcHeFf9yJvX-1AW0mAe8h4exNQ',
    appId: '1:969769036024:android:015218619fe37283f0730d',
    messagingSenderId: '969769036024',
    projectId: 'fitmetricsusers',
    storageBucket: 'fitmetricsusers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_5-LhxWyoW3welqhad_eDYZrLwoAq_gQ',
    appId: '1:969769036024:ios:2d1ba8a376353c70f0730d',
    messagingSenderId: '969769036024',
    projectId: 'fitmetricsusers',
    storageBucket: 'fitmetricsusers.firebasestorage.app',
    iosBundleId: 'com.example.fitMetrics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_5-LhxWyoW3welqhad_eDYZrLwoAq_gQ',
    appId: '1:969769036024:ios:2d1ba8a376353c70f0730d',
    messagingSenderId: '969769036024',
    projectId: 'fitmetricsusers',
    storageBucket: 'fitmetricsusers.firebasestorage.app',
    iosBundleId: 'com.example.fitMetrics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJV7ePDR14V2Jg5iDgO879K10y9-UV8BM',
    appId: '1:969769036024:web:c17bdc3bbfe3139df0730d',
    messagingSenderId: '969769036024',
    projectId: 'fitmetricsusers',
    authDomain: 'fitmetricsusers.firebaseapp.com',
    storageBucket: 'fitmetricsusers.firebasestorage.app',
    measurementId: 'G-BP9E3DNZ2N',
  );

}